dist: bionic
language: python
python:
  - 3.7
  - 3.6

install:
   - pip install -U tox-travis codecov
   - sudo apt-get install graphviz

script: travis_wait tox

after_success: codecov

deploy:

  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: master
      python: 3.7
