# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
  - 3.5

# Command to install dependencies
install: pip install -U tox-travis

# Command to run tests
script: travis_wait tox

deploy:

  # Automatically build and deploy documentation to GitHub Pages after every
  # commit
  # Follow the instructions at https://docs.travis-ci.com/user/deployment/pages/
  # to setup a personal deployment token and then provide it as a secure
  # environment variable at https://travis-ci.org/HDI-Project/mlprimitives/settings
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: master
      python: 3.6
